### ISSUE TITLE
Blank page when selecting language during initial setup

### ISSUE THREAD

**Issue by vstefanoxx** [opensupports/opensupports#1244]
**Bug/Actual behavior**
On the first step of initial setup, when selecting a different language a new blank page is loaded and an error is shown on the browser console. The problem occurrs only with the last version 4.11 and doesn't occur with version 4.10.

**Steps to reproduce**
1. Prepare a new installation of OpenSupports version 4.11
2. Access the homepage: the page `https://<domain>/install/step-1` is loaded
3. Select a different language from the dropdown menu (any language)
4. a new, blank page is loaded and an error is shown in the browser console (Chrome DevTools or equivalent)

**Expected behavior**
The page with the selected language should appears

**Additional context**
Error shown in the console of Chrome DevTools:

```
VM81:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at e.value (bundle.js:16:4483)
    at e.value (bundle.js:16:5836)
    at Object.<anonymous> (bundle.js:16:51110)
    at C (bundle.js:1:7843)
    at r (bundle.js:1:559)
    at Object.<anonymous> (bundle.js:21:4116)
    at C (bundle.js:1:7843)
    at r (bundle.js:1:559)
    at Object.<anonymous> (bundle.js:16:27479)
value @ bundle.js:16
value @ bundle.js:16
(anonymous) @ bundle.js:16
C @ bundle.js:1
r @ bundle.js:1
(anonymous) @ bundle.js:21
C @ bundle.js:1
r @ bundle.js:1
(anonymous) @ bundle.js:16
C @ bundle.js:1
r @ bundle.js:1
(anonymous) @ bundle.js:350
C @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
```

**System information**
OpenSupports version: 4.11

**Comment by KevinMarques** [comment]
Do not change the language during setup as a temporal workaround. Once the setup is finished everything works properly.
