### ISSUE TITLE
All 4 demo links on the opensupports.com demo page do not work

### ISSUE THREAD

**Issue by Superhands89** [opensupports/opensupports#1275]
https://www.opensupports.com/demo/

All 4 demo links open a blank page.

Tested in Latest Chrome on windows 11.

**Comment by DCCoder90** [comment]
Same results here, Edge on Windows 11.  Looking at the console I'm getting the following:

```
/api/system/installation-done:1 
        
        
        Failed to load resource: the server responded with a status of 500 (Internal Server Error)
bundle.js:9 INVALID REQUEST to: /system/installation-done
bundle.js:9 undefined
bundle.js:323  Uncaught (in promise) Error
    at bundle.js:323:285170
/api/system/get-settings:1 
        
        
        Failed to load resource: the server responded with a status of 500 (Internal Server Error)
bundle.js:9 INVALID REQUEST to: /system/get-settings
bundle.js:9 undefined
bundle.js:323  Uncaught (in promise) Error
    at bundle.js:323:285170
/api/user/check-session:1 
        
        
        Failed to load resource: the server responded with a status of 500 (Internal Server Error)
bundle.js:9 INVALID REQUEST to: /user/check-session
bundle.js:9 undefined
demo1.opensupports.com/:1  Uncaught (in promise) Object
```

**EDIT**

It appears that this project is dead in the water.  No one is maintaining or reviewing PRs.  May be best to move on.
