### ISSUE TITLE
Error when eMail-Polling

### ISSUE THREAD

**Issue by nickbe** [opensupports/opensupports#498]
The following error is reported by Apache when I try to poll some mail:

[Fri Mar 15 17:51:57.791221 2019] [php7:error] [pid 17724] [client xxxxxx.yyyyyy] PHP Fatal error:  Uncaught Error: Undefined class constant 'USER_SYSTEM' in /var/www/support/html/api/controllers/system/email-polling.php:33\nStack trace:\n#0 /var/www/support/html/api/libs/Controller.php(20): EmailPollingController->handler()\n#1 [internal function]: Controller->{closure}()\n#2 /var/www/support/html/api/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)\n#3 /var/www/support/html/api/vendor/slim/slim/Slim/Slim.php(1355): Slim\\Route->dispatch()\n#4 /var/www/support/html/api/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\\Slim->call()\n#5 /var/www/support/html/api/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\\Middleware\\Flash->call()\n#6 /var/www/support/html/api/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\\Middleware\\MethodOverride->call()\n#7 /var/www/support/html/api/vendor/slim/slim/Slim/Slim.php(1300): Slim\\Middleware\\PrettyExceptions->call()\n#8 /var/www/support/html/api/index.php(24): Slim\\Slim->run()\n#9 {main}\n  thr in /var/www/support/html/api/controllers/system/email-polling.php on line 33

**Comment by ivandiazwm** [comment]
Ok, this is an issue, it should use the contant `USER_SYSTEM_ENABLED`.
Also, if this error happens, it's because you're trying to use email polling while having the user system enabled, which is not possible.

**Comment by nickbe** [comment]
But wouldn't the enabled user system be exactly what we need?
This way you can run the incoming mail sender against the user database and allow only the registered mail adresses.

**Comment by TenGbps** [comment]
I have a error like 
`{"status":"fail","message":"INVALID_TOKEN","data":null}`
when am trying
curl -X POST -k -i 'https://support.stylograf.fr/api/system/email-polling' --data 'csrf_token=f44...................&csrf_userid=1'

**Comment by TenGbps** [comment]
I have a error like 
`{"status":"fail","message":"INVALID_TOKEN","data":null}`
when am trying
`curl -X POST -k -i 'https://support.mysystem/api/system/email-polling' --data 'csrf_token=f44...................&csrf_userid=1'`

**Comment by SunnyTeater** [comment]
@TenGbps 
Try  
https://localhost/admin/system/email-polling

I mean, if i try i get
> HTTP/1.1 200 OK
> Date: Wed, 03 Apr 2019 08:50:14 GMT
> Server: Apache/2.4.25 (Debian)
> Vary: Accept-Encoding
> Content-Length: 831
> Content-Type: text/html; charset=UTF-8
> X-Cache: MISS from barracuda1.bauking.ag
> Via: 1.1 barracuda1.bauking.ag (http_scan_byf/3.5.16)
> Connection: keep-alive
> 
> <!doctype html>
> <html class="no-js" lang="">
>     <head>
>         <meta charset="utf-8">
>         <meta http-equiv="X-UA-Compatible" content="IE=edge">
>         <meta name="description" content="">
>         <meta name="viewport" content="width=device-width">
> 
>         <title>OpenSupports</title>
> 
>         <link rel="stylesheet" href="http://localhost/css/main.css">
>         <link rel="icon" type="image/x-icon" href="http://localhost/images/icon.png">
>     </head>
>     <body>
>         <div id="app"></div>
> 
>         <script>
>             opensupports_version = '4.4.0';
>             root = "http://10.11.70.187";
>             apiRoot = 'http://localhost/api';
>             globalIndexPath = "";
>             showLogs = false;
>         </script>
>                 <script src="http://localhost/js/main.js"></script>
>     </body>
> </html>
> 

this is not fine ether but the http connection works.. :/

**Comment by SunnyTeater** [comment]
@ivandiazwm 
> Ok, this is an issue, it should use the contant USER_SYSTEM_ENABLED.

if i change it i´m getting a new error ^^

command:
`curl -X POST -k -i --data "token=DsEO7JVuJnP3L2tAwJOZ" http://localhost/api/system/email-polling`

apache log:

>  PHP Notice:  Unknown: SECURITY PROBLEM: insecure server advertised AUTH=PLAIN (errflg=1) in Unknown on line 0, referer: http://localhost/admin/panel/settings/email-settings

command error:

> HTTP/1.1 200 OK
Date: Wed, 03 Apr 2019 09:34:21 GMT
Server: Apache/2.4.25 (Debian)
Set-Cookie: PHPSESSID=9hlgo0rdbh7kq788htife4rhmn; path=/
Content-Length: 80
Content-Type: application/json
X-Cache: MISS from barracuda1.{serverdomain}.ag
Via: 1.1 barracuda1.{serverdomain}.ag (http_scan_byf/3.5.16)
Connection: keep-alive
>
>{"status":"fail","message":"Undefined property: stdClass::$subtype","data":null}root@debian:/var/log/apache2

**Comment by csaeum** [comment]
My mistake when trying to email polling with curl

>  /usr/local/pd-admin2/bin/curl -X POST -k -i --data "token=VgtkvW---------5Av" https://support.leder-stoffe-online.de/api/system/email-polling
> HTTP/1.1 500 Internal Server Error
> Date: Sat, 24 Aug 2019 23:27:04 GMT
> Server: Apache
> Set-Cookie: PHPSESSID=v35spejsn2v2424u22vhf3rs52; path=/
> Vary: Accept-Encoding,User-Agent
> Strict-Transport-Security: max-age=15768000
> Connection: close
> Transfer-Encoding: chunked
> Content-Type: text/html; charset=UTF-8

My error_log

> [Sun Aug 25 01:27:57 2019] [error] [client 5.189.184.182] FastCGI: server "/opt/pdadmin/etc/phpfcgi/lederdbh/starter" stderr: Stack trace:
> [Sun Aug 25 01:27:57 2019] [error] [client 5.189.184.182] FastCGI: server "/opt/pdadmin/etc/phpfcgi/lederdbh/starter" stderr: #0 /home/lederdbh/OpenSupports/api/libs/Controller.php(20): EmailPollingController->handler()
> [Sun Aug 25 01:27:57 2019] [error] [client 5.189.184.182] FastCGI: server "/opt/pdadmin/etc/phpfcgi/lederdbh/starter" stderr: #1 [internal function]: Controller->{closure}()
> [Sun Aug 25 01:27:57 2019] [error] [client 5.189.184.182] FastCGI: server "/opt/pdadmin/etc/phpfcgi/lederdbh/starter" stderr: #2 /home/lederdbh/OpenSupports/api/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
> [Sun Aug 25 01:27:57 2019] [error] [client 5.189.184.182] FastCGI: server "/opt/pdadmin/etc/phpfcgi/lederdbh/starter" stderr: #3 /home/lederdbh/OpenSupports/api/vendor/slim/slim/Slim/Slim.php(1355): Slim\\Route->dispatch()
> [Sun Aug 25 01:27:57 2019] [error] [client 5.189.184.182] FastCGI: server "/opt/pdadmin/etc/phpfcgi/lederdbh/starter" stderr: #4 /home/lederdbh/OpenSupports/api/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\\Slim->call()
> [Sun Aug 25 01:27:57 2019] [error] [client 5.189.184.182] FastCGI: server "/opt/pdadmin/etc/phpfcgi/lederdbh/starter" stderr: #5 /home/lederdbh/OpenSupports/api/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\\Middleware\\Flash->call()
> [Sun Aug 25 01:27:57 2019] [error] [client 5.189.184.182] FastCGI: server "/opt/pdadmin/etc/phpfcgi/lederdbh/starter" stderr: #6 /home/lederdbh/OpenSupports/api/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\\Middleware\\MethodOverride->call()
> [Sun Aug 25 01:27:57 2019] [error] [client 5.189.184.182] FastCGI: server "/opt/pdadmin/etc/phpfcgi/lederdbh/starter" stderr: #7 /home/lederdbh/OpenSupports/api/vendor/slim/slim/Slim/Slim.php(1300): Slim\\Middleware\\PrettyExceptions->call()
> [Sun Aug 25 01:27:57 2019] [error] [client 5.189.184.182] FastCGI: server "/opt/pdadmin/etc/phpfcgi/lederdbh/starter" stderr: #8 /home/lederdbh/OpenSupports/api/index.php(24): Slim\\ in /home/lederdbh/OpenSupports/api/controllers/system/email-polling.php on line 33

**Comment by baxandrei** [comment]
I have same issue: ```Fatal error: Uncaught Error: Call to undefined method NullDataStore::canManageTicket() in /home/baxandrei/public_html/help/api/controllers/ticket/comment.php:90 Stack trace: #0 /home/baxandrei/public_html/help/api/controllers/system/email-polling.php(92): CommentController->handler() #1 /home/baxandrei/public_html/help/api/libs/Controller.php(20): EmailPollingController->handler() #2 [internal function]: Controller->{closure}() #3 /home/baxandrei/public_html/help/api/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array) #4 /home/baxandrei/public_html/help/api/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch() #5 /home/baxandrei/public_html/help/api/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call() #6 /home/baxandrei/public_html/help/api/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call() #7 /home/baxandrei/public_html/help/api/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call() #8 /home/b in /home/baxandrei/public_html/help/api/controllers/ticket/comment.php on line 90```

I think because of this email (when I delete it, all works great), where a user replied back to it:
![image](https://user-images.githubusercontent.com/12484505/69364447-fdc0f680-0c9a-11ea-85e9-02a1c9ea0cb0.png)

**Comment by pieter-groeneweg** [comment]
Same issue here... 

Also I am with @nickbe A combination of the two is what would be nice.
Allow emails sent and matched against the existing users.
And in addition, emails not matched will only be picked up after user has been added. 

This way some filtering can be done and spam, that passes all filters and ban lists, refused before having to set them in the blocked list.

Tx

**Comment by doybenz11** [comment]
Hi! Please help.

curl -k -i -X POST --data "token=aM0cwvq0cGeISUXnKzt1" http://localhost/opensupports/api/system/email-polling

HTTP/1.1 200 OK
Date: Fri, 27 Dec 2019 22:37:57 GMT
Server: Apache/2.4.18 (Ubuntu)
Set-Cookie: PHPSESSID=di80r7uo07luelvmtcnc1o3vm7; path=/
Content-Length: 146
Content-Type: application/json

{"status":"fail","message":"\"UTF-8\" is not supported by setServerEncoding(). Your system only supports these encodings: US-ASCII, ","data":null}

**Comment by AngryGinger** [comment]
I have the same issue : 
C:\Users\SERV-SAV>curl --data "token=YXTX7AQxe3pDkuVixt0e" http://localhost/ticket/api/system/email-polling
{"status":"fail","message":"USER_SYSTEM_ENABLED","data":null}

**Comment by maurizioghielmetti** [comment]
Hi guys, could anyone solve this issue?

I get these different outputs

curl --data "csrf_token=xxxtokenxxx" http://siteurl/api/system/email-polling
{"status":"fail","message":"INVALID_TOKEN","data":null}

curl --data "token=xxxtokenxxx" http://siteurl/api/system/email-polling
{"status":"fail","message":"NO_PERMISSION","data":null}

I can't find anything about USER_SYSTEM_ENABLED and where to disable it
The token is set and Imap parameter are fine. One user enabled and linked to a department.

Is there anyone willing to help me, please?
Thank you

**Comment by dotupNET** [comment]
You've to use the token=IMAP-Token
Where IMAP-Token is the value from email settings
