### ISSUE TITLE
SMTP failed connection

### ISSUE THREAD

**Issue by Dorsdre** [opensupports/opensupports#504]
Hi OpenSupports Team.

I have a problem configuring the SMTP server, I'm installing for the first time and the latest version, I have seen the guide in the wiki tab and the video in YouTube to configure the SMTP server but it has not worked for me, I get SMTP_CONNECTION error.

I have tried with several gmail accounts that I use for sending emails and that I know that they have enabled the smtp connection of gmail for external software but it doesn't work.

I have tried with: tls://smtp.gmail.com:587, smtp.gmail.com:25, also trying with ssl : ssl://smtp.gmail.com: 465.
I verified the credentials of the emails and entered them in the configuration as they are, but it doesn't work.

![SMPT Details](https://user-images.githubusercontent.com/40363755/54694863-f1c2da80-4af6-11e9-8b66-9a4b6f4cbd57.png)
![Error SMTP](https://user-images.githubusercontent.com/40363755/54694870-f4253480-4af6-11e9-9af3-ef86a7360cc8.png)

**Comment by goldleewtje** [comment]
have you tried it with port 587?

**Comment by Dorsdre** [comment]
Yes, i have tried it, you can see the illustrative image that i'm trying it in the SMPT Server.

**Comment by Dorsdre** [comment]
Can someone help me?, I have not been able to solve the problem and therefore I do not have the system with notifications by mail.
Thanks.

**Comment by Evolusie-dev** [comment]
I have the same error, I just installed it with my CPanel and cloud host, and everything is well except setting up the SMTP Server, exactly same error.
Any solution ?.

**Comment by nickbe** [comment]
This could be due to a gmail configuration problem. Have you allwed insecure apps to connect to gmail?
Have you checked the current gmail documentation for smtp scencarios?

I can only advise NOT to use gmail in the first place. We had so many problems with gmail servers over the years that they are in no way reliable for us. Just use any other standard mail server like we do and you should be good to go.

**Comment by SunnyTeater** [comment]
enter the password again.
I think this is an error, if you click "test" the system uses the password "HIDDEN" which is maybe not your password?

Had the same issues with IMAP.

**Comment by DorianMaliszewski** [comment]
I have the same error with my own postfix server :
- tls://mail.****************.fr:587
- username
- password

But it works with google, SMTP Tester, Thunderbird, Mailspring.

Anyone have an idea ? I have this in my getMailerInstance :

```
private function getMailerInstance() {
        if(!($this->mailerInstance instanceof PHPMailer)) {
            $this->mailerInstance = new PHPMailer();

            $this->mailerInstance->From = $this->mailOptions['from'];
            $this->mailerInstance->FromName = $this->mailOptions['fromName'];
            $this->mailerInstance->CharSet = 'UTF-8';

            $this->mailerInstance->isSMTP();
            $this->mailerInstance->SMTPAuth = true;
            $this->mailerInstance->Host = $this->mailOptions['smtp-host'];
            $this->mailerInstance->Username = $this->mailOptions['smtp-user'];
            $this->mailerInstance->Password = $this->mailOptions['smtp-pass'];
            $this->mailerInstance->Timeout = 10;
            $this->mailerInstance->SMTPSecure = 'tls';
            $this->mailerInstance->SMTPOptions = [
                'ssl' => [
                    'verify_peer' => false,
                    'verify_peer_name' => false,
                    'allow_self_signed' => true
                ]
            ];
        }

        return $this->mailerInstance;
    }

```

**Comment by willadam** [comment]
> I have the same error with my own postfix server :
> 
> * tls://mail.****************.fr:587
> * username
> * password
> 
> But it works with google, SMTP Tester, Thunderbird, Mailspring.
> 
> Anyone have an idea ? I have this in my getMailerInstance :
> 
> ```
> private function getMailerInstance() {
>         if(!($this->mailerInstance instanceof PHPMailer)) {
>             $this->mailerInstance = new PHPMailer();
> 
>             $this->mailerInstance->From = $this->mailOptions['from'];
>             $this->mailerInstance->FromName = $this->mailOptions['fromName'];
>             $this->mailerInstance->CharSet = 'UTF-8';
> 
>             $this->mailerInstance->isSMTP();
>             $this->mailerInstance->SMTPAuth = true;
>             $this->mailerInstance->Host = $this->mailOptions['smtp-host'];
>             $this->mailerInstance->Username = $this->mailOptions['smtp-user'];
>             $this->mailerInstance->Password = $this->mailOptions['smtp-pass'];
>             $this->mailerInstance->Timeout = 10;
>             $this->mailerInstance->SMTPSecure = 'tls';
>             $this->mailerInstance->SMTPOptions = [
>                 'ssl' => [
>                     'verify_peer' => false,
>                     'verify_peer_name' => false,
>                     'allow_self_signed' => true
>                 ]
>             ];
>         }
> 
>         return $this->mailerInstance;
>     }
> ```

What settings did you use for it to work with Google? I can't get it to work with anything...

Any help would be great! :-)

**Comment by DorianMaliszewski** [comment]
I resolved this issue with :

- Reinstall OpenSupports with last version.
- Configure SMTP with:

```
tls://**********.fr:587
user@maildomain.fr
myuserpassword
```

And all nice.

Thanks you for your time :smile:

**Comment by goldleewtje** [comment]
then i dont knwo how to help any further maybe you can contact one of the devs about it?

**Comment by Mte90** [comment]
I tried to reach the developers also on Twitter but no one is replying to me.

**Comment by DorianMaliszewski** [comment]
Can you put your source code of api/libs/MailSender.php. Is your SMTP Server is private or mutualised (OVH, 1&1, Google, ...).
Did you try to test your smtp with another tool ? (ex: https://www.smtper.net/)

**Comment by goldleewtje** [comment]
have you tried to use the gmail smtp server? that way you can check if it is your smtp server that is not working or something in the code.

**Comment by Mte90** [comment]
The smtp works because if in the settings page I use the domain and password and do the tests affirm that everything is ok but after save is not working.
So it is like that something in the db isn't good for who update the system and for new install there are no problems.

**Comment by Mte90** [comment]
As I written in #521 the server is working and also opensupports but not on when there is to send emails for tickets or anywhere outside the settings.
The data are saved inside the db in the right way, the smtp host is working because I used before the upgrade, the test system in the settings works and I use the same server also for other emails.

**Comment by IsaacHats** [comment]
Hello, I am having the same issue, How do I change/check the port? I have looked almost everywhere.

**Comment by Mte90** [comment]
I tried with a backport and now was working everything but I tried to update to 4.4.0 and I am getting that:
```
Begin update v4.4.0...
[1/1] Update email settings..
<br />
<b>Fatal error</b>:  Uncaught RedBeanPHP\RedException: OODB Store requires a bean, got: NULL in api/vendor/gabordemooij/redbean/RedBeanPHP/OODB.php:119
Stack trace:
#0 api/vendor/gabordemooij/redbean/RedBeanPHP/OODB.php(404): RedBeanPHP\OODB-&gt;unboxIfNeeded(NULL)
#1 /api/vendor/gabordemooij/redbean/RedBeanPHP/Facade.php(544): RedBeanPHP\OODB-&gt;trash(NULL)
#2 /api/models/DataStore.php(136): RedBeanPHP\Facade::trash(NULL)
#3 /version_upgrades/4.4.0/4.4.0.php(36): DataStore-&gt;delete()
#4 {main}
  thrown in <b>/api/vendor/gabordemooij/redbean/RedBeanPHP/OODB.php</b> on line <b>119</b><br />

```

**Comment by DorianMaliszewski** [comment]
> Hello, I am having the same issue, How do I change/check the port? I have looked almost everywhere.

Try to test your smtp with a tool ? (ex: https://www.smtper.net/).  
Put something like in the configurations :
```
tls://**********.fr:587
user@maildomain.fr
myuserpassword
```

**Comment by DorianMaliszewski** [comment]
> I tried with a backport and now was working everything but I tried to update to 4.4.0 and I am getting that:
> 
> ```
> Begin update v4.4.0...
> [1/1] Update email settings..
> <br />
> <b>Fatal error</b>:  Uncaught RedBeanPHP\RedException: OODB Store requires a bean, got: NULL in api/vendor/gabordemooij/redbean/RedBeanPHP/OODB.php:119
> Stack trace:
> #0 api/vendor/gabordemooij/redbean/RedBeanPHP/OODB.php(404): RedBeanPHP\OODB-&gt;unboxIfNeeded(NULL)
> #1 /api/vendor/gabordemooij/redbean/RedBeanPHP/Facade.php(544): RedBeanPHP\OODB-&gt;trash(NULL)
> #2 /api/models/DataStore.php(136): RedBeanPHP\Facade::trash(NULL)
> #3 /version_upgrades/4.4.0/4.4.0.php(36): DataStore-&gt;delete()
> #4 {main}
>   thrown in <b>/api/vendor/gabordemooij/redbean/RedBeanPHP/OODB.php</b> on line <b>119</b><br />
> ```

I don't know how to solve your problem, may be the better solution is to reinstall with the last version.
Last chance is to go in the code of RedBean and debug it :disappointed:

**Comment by matheuscomaru** [comment]
Boa noite, estou com o mesmo problema, já tem alguma previsão para a solução do mesmo ?

**Comment by 51n15tr0** [comment]
> > Eu tenho o mesmo erro com meu próprio servidor Postfix:
> > 
> > * tls: //mail.*****************.fr: 587
> > * nome de usuário
> > * senha
> > 
> > Mas funciona com google, SMTP Tester, Thunderbird, Mailspring.
> > Alguém tem uma ideia ? Eu tenho isso em meu getMailerInstance:
> > ```
> > private function getMailerInstance() {
> >         if(!($this->mailerInstance instanceof PHPMailer)) {
> >             $this->mailerInstance = new PHPMailer();
> > 
> >             $this->mailerInstance->From = $this->mailOptions['from'];
> >             $this->mailerInstance->FromName = $this->mailOptions['fromName'];
> >             $this->mailerInstance->CharSet = 'UTF-8';
> > 
> >             $this->mailerInstance->isSMTP();
> >             $this->mailerInstance->SMTPAuth = true;
> >             $this->mailerInstance->Host = $this->mailOptions['smtp-host'];
> >             $this->mailerInstance->Username = $this->mailOptions['smtp-user'];
> >             $this->mailerInstance->Password = $this->mailOptions['smtp-pass'];
> >             $this->mailerInstance->Timeout = 10;
> >             $this->mailerInstance->SMTPSecure = 'tls';
> >             $this->mailerInstance->SMTPOptions = [
> >                 'ssl' => [
> >                     'verify_peer' => false,
> >                     'verify_peer_name' => false,
> >                     'allow_self_signed' => true
> >                 ]
> >             ];
> >         }
> > 
> >         return $this->mailerInstance;
> >     }
> > ```
> 
> Quais configurações você usou para que ele funcionasse com o Google? Não consigo fazer funcionar com nada ...
> 
> Qualquer ajuda seria ótimo! :-)

hello friend, i was having the same problem in gmail, but i managed to solve it by going to:> google account> security> less secure app access, when you get there you will see that this option will be disabled, activate it and then go back to opensupports and do the test again, with me it was quick and it worked magically.

**Comment by next-andre-gama** [comment]
Bom dia pessoal, quando eu pressiono o botão teste dar esse erro que que foi mostrado no inicio "SMTP_CONNECTION", ai com isso eu fui ver o valor que está no input da senha ai notei que nele fica o valor 'HIDDEN', sei que a ideia é deixar a senha escondida, mas pelo que estou vendo ele manda o HIDDEN como se fosse a senha do e-mail por esse motivo dar o erro. Quando eu apago esse HIDDEN e coloco a senha do e-mail correto ele faz o teste correto e logo depois quando salvo e fica o valor HIDDEN no input volta a dar erro.

Sei que não é de muita ajuda mas estou vendo isso ainda, mas espero ajudar alguém com isso.

![image](https://user-images.githubusercontent.com/49646623/123100696-b61bc700-d409-11eb-83fa-369151cc5d26.png)

**Comment by marcoscarraro** [comment]
Resolved on code.
Replaced this $this->mailerInstance->From = $this->mailOptions['from']; for $this->mailerInstance->From = $this->mailOptions['smtp-user'];

Because the server smtp require "from" is same user authenticade.

**Comment by Allis0nMatos** [comment]
Good afternoon, I have a similar problem, the SMTP server when you do a connection test it connects, but when I create the call it does not send the email to the administrators, can someone tell me how to solve it?

**Comment by AtomicGaming666** [comment]
hello I'm using zoho mailing for my SMTP stuff but I keep getting the error that's in the title on this issue

**Comment by madfunny** [comment]
Are you using the zoho settings in opensupports?

Zoho.com (Zoho Mail) SMTP Server*smtp.zoho.com <http://smtp.zoho.com>*
SMTP port 587
SMTP security STARTTLS
SMTP username Your full email address
SMTP password Your Zoho.com password

- Chaos / Dissolvanizer

ChaosVoid

**Comment by AtomicGaming666** [comment]
yes thats what im using
