### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method NullDataStore::getSubject()

### ISSUE THREAD

**Issue by Mte90** [opensupports/opensupports#521]
```

Fatal error: Uncaught Error: Call to undefined method NullDataStore::getSubject() in /api/libs/MailSender.php:30 Stack trace: 
#0 /api/controllers/ticket/create.php(189): MailSender->setTemplate('TICKET_CREATED_...', Array) 
#1 /api/controllers/ticket/create.php(114): CreateController->sendMailStaff('email@hidden....') 
#2 api/libs/Controller.php(20): CreateController->handler() 
#3 [internal function]: Controller->{closure}() 
#4 /api/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array) 
#5 /api/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch() 
#6 /api/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call() 
#7 /api/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call() #8 in /api/libs/MailSender.php on line 30
```

My user cannot create tickets for this error

**Comment by Mte90** [comment]
ping

**Comment by Mte90** [comment]
I think that is the same of https://github.com/opensupports/opensupports/issues/504 https://github.com/opensupports/opensupports/issues/522

**Comment by Mte90** [comment]
With the previous version I have still the same problem:

```
uncaught exception: <br /> <b>Fatal error</b>: 
Uncaught Error: Call to undefined method NullDataStore::getSubject() in 
api/libs/MailSender.php:32 Stack trace: #0 
/api/controllers/ticket/close.php(113): MailSender-&gt;setTemplate('TICKET_CLOSED', Array) 
#1 /api/controllers/ticket/close.php(79): CloseController-&gt;sendMail() 
#2 /api/libs/Controller.php(20): CloseController-&gt;handler() 
#3 [internal function]: Controller-&gt;{closure}() 
#4 api/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array) 
#5 /api/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route-&gt;dispatch() 
#6 /api/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim-&gt;call() 
#7 /api/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash-&gt;call() 
#8 /api/vendor/slim/slim/ in <b>/api/libs/MailSender.php</b> on line <b>32</b><br /> 
```

**Comment by Mte90** [comment]
Seems that was missing a previous upgrade to 4.3.2 and now this error is not happening anymore.
