### ISSUE TITLE
IMAP ticket creation only works for the first email

### ISSUE THREAD

**Issue by lidfill** [opensupports/opensupports#528]
I have setup the IMAP Server and tested it with success, when i send an email for the first time and run the polling POST it works fine and creates a ticket, but when there is a second email or i send a new one and run the polling it fails and deletes the emails from the inbox but does **not** create a ticket, if i login to the database and manually delete the ticket, the next email will create a ticket successfully, so it only works if there is not already a ticket in the system...

The error i receive from the POST:

> {"status":"fail","message":"EMAIL_POLLING","data":[{"author":"example@example.com","ticketNumber":null,"error":"Exception: LinearCongruentialGenerator: gap must be prime in \/home2\/flagcom\/public_html\/support\/api\/libs\/LinearCongruentialGenerator.php:14\nStack trace:\n#0 \/home2\/flagcom\/public_html\/support\/api\/models\/Ticket.php(105): LinearCongruentialGenerator->setGap('3046659')\n#1 \/home2\/flagcom\/public_html\/support\/api\/models\/Ticket.php(86): Ticket->generateUniqueTicketNumber()\n#2 \/home2\/flagcom\/public_html\/support\/api\/models\/DataStore.php(72): Ticket->getDefaultProps()\n#3 \/home2\/flagcom\/public_html\/support\/api\/controllers\/ticket\/create.php(127): DataStore->__construct()\n#4 \/home2\/flagcom\/public_html\/support\/api\/controllers\/ticket\/create.php(105): CreateController->storeTicket()\n#5 \/home2\/flagcom\/public_html\/support\/api\/controllers\/system\/email-polling.php(95): CreateController->handler()\n#6 \/home2\/flagcom\/public_html\/support\/api\/libs\/Controller.php(20): EmailPollingController->handler()\n#7 [internal function]: Controller->{closure}()\n#8 \/home2\/flagcom\/public_html\/support\/api\/vendor\/slim\/slim\/Slim\/Route.php(468): call_user_func_array(Object(Closure), Array)\n#9 \/home2\/flagcom\/public_html\/support\/api\/vendor\/slim\/slim\/Slim\/Slim.php(1355): Slim\\Route->dispatch()\n#10 \/home2\/flagcom\/public_html\/support\/api\/vendor\/slim\/slim\/Slim\/Middleware\/Flash.php(85): Slim\\Slim->call()\n#11 \/home2\/flagcom\/public_html\/support\/api\/vendor\/slim\/slim\/Slim\/Middleware\/MethodOverride.php(92): Slim\\Middleware\\Flash->call()\n#12 \/home2\/flagcom\/public_html\/support\/api\/vendor\/slim\/slim\/Slim\/Middleware\/PrettyExceptions.php(67): Slim\\Middleware\\MethodOverride->call()\n#13 \/home2\/flagcom\/public_html\/support\/api\/vendor\/slim\/slim\/Slim\/Slim.php(1300): Slim\\Middleware\\PrettyExceptions->call()\n#14 \/home2\/flagcom\/public_html\/support\/api\/index.php(24): Slim\\Slim->run()\n#15 {main}"}]}

**Comment by lidfill** [comment]
Might not be anything to do with IMAP, that's just how i was planning to use the system, seems the issue occurs when trying to create a second ticket directly in the portal while there is nothing in the database.

**Comment by emunizaga** [comment]
The error says: "gap must be prime in" It is necessary to change the ticket-gap field of the setting table, by a prime number like 15485863 and it worked for me

**Comment by jemz** [comment]
Unbelievable but @emunizaga is right, just happened to me and changed the value in the table. Fixed.
