### ISSUE TITLE
POST setup

### ISSUE THREAD

**Issue by esgaroth1284** [opensupports/opensupports#560]
Good day, 

I am hoping someone can assist me in doing the POST request. Can I just paste the url into a browser and it should do the request? how should the string look?

Also, I tried the request with curl and fetch on a mikrotik so that I can schedule it to run every 2minutes or so. 

But I just get the following error:
404 Page not found.

**Comment by esgaroth1284** [comment]
More information regarding curl output

root@cacti:~# curl -X POST -k -i --data "token=blahblah123blah" http://ticketsystem.tic/api/system/email-polling
HTTP/1.1 200 OK
Date: Mon, 10 Jun 2019 10:50:04 GMT
Server: Apache
Set-Cookie: PHPSESSID=aahheeyeyuu22333kakaf; path=/
Vary: Accept-Encoding
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8


Fatal error: Undefined class constant 'USER_SYSTEM' in /usr/www/users/blahblah/api/controllers/system/email-polling.php on line 33

**Comment by esgaroth1284** [comment]
Also, 

When I use fetch I get the following:

> tool fetch http-method=post http-data="token=blahblaht0k3n"  url="http://blahblah.com
/api/system/email-polling"            
      status: finished
  downloaded: 0KiBC-z pause]
    duration: 1s

But it does not fetch the e-mail and convert to ticket

**Comment by esgaroth1284** [comment]
I disabled the user system and it is working. But responding on the ticket does not send a reply e-mail

**Comment by esgaroth1284** [comment]
Found this:
root@prox1:~# curl -X POST -k -i --data "token=fIqkdIVIzUdfrhgfshgfsgj" http://ticket.tic/api/system/email-polling
HTTP/1.1 200 OK
Date: Thu, 13 Jun 2019 08:55:47 GMT
Server: Apache
Set-Cookie: PHPSESSID=t91chce5ctu2ua20dp6vcs4q87; path=/
Transfer-Encoding: chunked
Content-Type: application/json

{"status":"fail","message":"EMAIL_POLLING","data":[{"author":"support@ticket.tic","ticketNumber":null,"error":"exception 'Exception' with message 'LinearCongruentialGenerator: gap must be prime' in \/usr\/www\/users\/futurkfqhb\/api\/libs\/LinearCongruentialGenerator.php:14\nStack trace:\n#0 \/usr\/www\/users\/futurkfqhb\/api\/models\/Ticket.php(105): LinearCongruentialGenerator->setGap('1')\n#1 \/usr\/www\/users\/futurkfqhb\/api\/models\/Ticket.php(86): Ticket->generateUniqueTicketNumber()\n#2 \/usr\/www\/users\/futurkfqhb\/api\/models\/DataStore.php(72): Ticket->getDefaultProps()\n#3 \/usr\/www\/users\/futurkfqhb\/api\/controllers\/ticket\/create.php(127): DataStore->__construct()\n#4 \/usr\/www\/users\/futurkfqhb\/api\/controllers\/ticket\/create.php(105): CreateController->storeTicket()\n#5 \/usr\/www\/users\/futurkfqhb\/api\/controllers\/system\/email-polling.php(95): CreateController->handler()\n#6 \/usr\/www\/users\/futurkfqhb\/api\/libs\/Controller.php(20): EmailPollingController->handler()\n#7 [internal function]: Controller->{closure}()\n#8 \/usr\/www\/users\/futurkfqhb\/api\/vendor\/slim\/slim\/Slim\/Route.php(468): call_user_func_array(Object(Closure), Array)\n#9 \/usr\/www\/users\/futurkfqhb\/api\/vendor\/slim\/slim\/Slim\/Slim.php(1355): Slim\\Route->dispatch()\n#10 \/usr\/www\/users\/futurkfqhb\/api\/vendor\/slim\/slim\/Slim\/Middleware\/Flash.php(85): Slim\\Slim->call()\n#11 \/usr\/www\/users\/futurkfqhb\/api\/vendor\/slim\/slim\/Slim\/Middleware\/MethodOverride.php(92): Slim\\Middleware\\Flash->call()\n#12 \/usr\/www\/users\/futurkfqhb\/api\/vendor\/slim\/slim\/Slim\/Middleware\/PrettyExceptions.php(67): Slim\\Middleware\\MethodOverride->call()\n#13 \/usr\/www\/users\/futurkfqhb\/api\/vendor\/slim\/slim\/Slim\/Slim.php(1300): Slim\\Middleware\\PrettyExceptions->call()\n#14 \/usr\/www\/users\/futurkfqhb\/api\/index.php(24): Slim\\Slim->run()\n


also

root@prox1:~# curl -X POST -k -i --data "token=fIqkdIVIzUdfrhgfshgfsgj" http://ticket.tic/api/system/email-polling
HTTP/1.1 200 OK
Date: Thu, 13 Jun 2019 08:51:10 GMT
Server: Apache
Set-Cookie: PHPSESSID=0gjpmdigf8ijod223rsja3hev5; path=/
Transfer-Encoding: chunked
Content-Type: application/json

{"status":"fail","message":"EMAIL_POLLING","data":[{"author":"testuser@gmail.com","ticketNumber":null,"error":"exception 'Exception' with message 'LinearCongruentialGenerator: gap must be prime' in \/usr\/www\/users\/futurkfqhb\/api\/libs\/LinearCongruentialGenerator.php:14\nStack trace:\n#0 \/usr\/www\/users\/futurkfqhb\/api\/models\/Ticket.php(105): LinearCongruentialGenerator->setGap('1')\n#1 \/usr\/www\/users\/futurkfqhb\/api\/models\/Ticket.php(86): Ticket->generateUniqueTicketNumber()\n#2 \/usr\/www\/users\/futurkfqhb\/api\/models\/DataStore.php(72): Ticket->getDefaultProps()\n#3 \/usr\/www\/users\/futurkfqhb\/api\/controllers\/ticket\/create.php(127): DataStore->__construct()\n#4 \/usr\/www\/users\/futurkfqhb\/api\/controllers\/ticket\/create.php(105): CreateController->storeTicket()\n#5 \/usr\/www\/users\/futurkfqhb\/api\/controllers\/system\/email-polling.php(95): CreateController->handler()\n#6 \/usr\/www\/users\/futurkfqhb\/api\/libs\/Controller.php(20): EmailPollingController->handler()\n#7 [internal function]: Controller->{closure}()\n#8 \/usr\/www\/users\/futurkfqhb\/api\/vendor\/slim\/slim\/Slim\/Route.php(468): call_user_func_array(Object(Closure), Array)\n#9 \/usr\/www\/users\/futurkfqhb\/api\/vendor\/slim\/slim\/Slim\/Slim.php(1355): Slim\\Route->dispatch()\n#10 \/usr\/www\/users\/futurkfqhb\/api\/vendor\/slim\/slim\/Slim\/Middleware\/Flash.php(85): Slim\\Slim->call()\n#11 \/usr\/www\/users\/futurkfqhb\/api\/vendor\/slim\/slim\/Slim\/Middleware\/MethodOverride.php(92): Slim\\Middleware\\Flash->call()\n#12 \/usr\/www\/users\/futurkfqhb\/api\/vendor\/slim\/slim\/Slim\/Middleware\/PrettyExceptions.php(67): Slim\\Middleware\\MethodOverride->call()\n#13 \/usr\/www\/users\/futurkfqhb\/api\/vendor\/slim\/slim\/Slim\/Slim.php(1300): Slim\\Middleware\\PrettyExceptions->call()\n#14 \/usr\/www\/users\/futurkfqhb\/api\/index.php(24): Slim\\Slim->run()\n#15 {main}"}]}

**Comment by esgaroth1284** [comment]
I found a way around this. I changed the ticket-gap in phpmyadmin under settings to 2 instead of 1. Not sure if "1" causes some issues but setting it to "2" resolved my issue. Tickets generate nou from 100000, 100002, 100004 etc...
