### ISSUE TITLE
IMAP POST error 500

### ISSUE THREAD

**Issue by brunocamacho** [opensupports/opensupports#563]
I'm trying to setup the email polling on my server, but the post request returns http error 500...

When I try this: `curl -X POST -k -i --data "token=HIwIbt6V6SzNoCBq7RFC" https://domain.tld/opensupport/api/system/email-polling`

the response I get is:

HTTP/1.1 500 Internal Server Error
Set-Cookie: PHPSESSID=f6bf5bad7a9022adfa3ab7d072df4e41; path=/
Content-Type: text/html; charset=UTF-8
Content-Length: 0
Date: Tue, 11 Jun 2019 23:53:04 GMT
Server: LiteSpeed
Alt-Svc: quic=":443"; ma=2592000; v="35,39,43,44"
Connection: Keep-Alive

Any idea on how to fix? Using version 4.4.0 of opensupport...

**Comment by milancio** [comment]
I have the same problem

**Comment by ivandiazwm** [comment]
Do you have any result in your server logs?
Take into account that IMAP is only available when you have the user system disabled. If not, there's a `USER_SYSTEM` constant error that is throwing a `500` now.

**Comment by brunocamacho** [comment]
Ok, I disabled the user system, but now I get the following error:

{"status":"fail","message":"EMAIL_POLLING","data":[{"author":"brunovinicius.camacho@gmail.com","ticketNumber":null,"error":"Exception: LinearCongruentialGenerator: gap must be prime in \/home\/infolaye\/imascalendariosbl.tk\/opensupport\/api\/libs\/LinearCongruentialGenerator.php:14\nStack trace:\n#0 \/home\/infolaye\/imascalendariosbl.tk\/opensupport\/api\/models\/Ticket.php(105): LinearCongruentialGenerator->setGap('1918353')\n#1 \/home\/infolaye\/imascalendariosbl.tk\/opensupport\/api\/models\/Ticket.php(86): Ticket->generateUniqueTicketNumber()\n#2 \/home\/infolaye\/imascalendariosbl.tk\/opensupport\/api\/models\/DataStore.php(72): Ticket->getDefaultProps()\n#3 \/home\/infolaye\/imascalendariosbl.tk\/opensupport\/api\/controllers\/ticket\/create.php(127): DataStore->__construct()\n#4 \/home\/infolaye\/imascalendariosbl.tk\/opensupport\/api\/controllers\/ticket\/create.php(105): CreateController->storeTicket()\n#5 \/home\/infolaye\/imascalendariosbl.tk\/opensupport\/api\/controllers\/system\/email-polling.php(95): CreateController->handler()\n#6 \/home\/infolaye\/imascalendariosbl.tk\/opensupport\/api\/libs\/Controller.php(20): EmailPollingController->handler()\n#7 [internal function]: Controller->{closure}()\n#8 \/home\/infolaye\/imascalendariosbl.tk\/opensupport\/api\/vendor\/slim\/slim\/Slim\/Route.php(468): call_user_func_array(Object(Closure), Array)\n#9 \/home\/infolaye\/imascalendariosbl.tk\/opensupport\/api\/vendor\/slim\/slim\/Slim\/Slim.php(1355): Slim\\Route->dispatch()\n#10 \/home\/infolaye\/imascalendariosbl.tk\/opensupport\/api\/vendor\/slim\/slim\/Slim\/Middleware\/Flash.php(85): Slim\\Slim->call()\n#11 \/home\/infolaye\/imascalendariosbl.tk\/opensupport\/api\/vendor\/slim\/slim\/Slim\/Middleware\/MethodOverride.php(92): Slim\\Middleware\\Flash->call()\n#12 \/home\/infolaye\/imascalendariosbl.tk\/opensupport\/api\/vendor\/slim\/slim\/Slim\/Middleware\/PrettyExceptions.php(67): Slim\\Middleware\\MethodOverride->call()\n#13 \/home\/infolaye\/imascalendariosbl.tk\/opensupport\/api\/vendor\/slim\/slim\/Slim\/Slim.php(1300): Slim\\Middleware\\PrettyExceptions->call()\n#14 \/home\/infolaye\/imascalendariosbl.tk\/opensupport\/api\/index.php(24): Slim\\Slim->run()\n#15 {main}"}]}

**Comment by esgaroth1284** [comment]
I had the same issue, I disabled the user system and it is creating the ticket from e-mail

**Comment by esgaroth1284** [comment]
I found a way around this. I changed the ticket-gap in phpmyadmin under settings to 2 instead of 1. Not sure if "1" causes some issues but setting it to "2" resolved my issue. Tickets generate nou from 100000, 100002, 100004 etc...
