### ISSUE TITLE
Users unable to respond to their tickets

### ISSUE THREAD

**Issue by toppestofhatts** [opensupports/opensupports#702]
Hi,
For whatever reason, with all files being default, when I attempt to reply to a ticket (as the user who made it), it comes up with a post error like this: http://prntscr.com/qrrgfz. Staff are able to reply however.
This is what's in the error log:
[23-Jan-2020 12:03:11 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method NullDataStore::canManageTicket() in /home/jlulr7ouwc1u/public_html/support/api/controllers/ticket/comment.php:90
Stack trace:
#0 /home/jlulr7ouwc1u/public_html/support/api/libs/Controller.php(20): CommentController->handler()
#1 [internal function]: Controller->{closure}()
#2 /home/jlulr7ouwc1u/public_html/support/api/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#3 /home/jlulr7ouwc1u/public_html/support/api/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
#4 /home/jlulr7ouwc1u/public_html/support/api/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#5 /home/jlulr7ouwc1u/public_html/support/api/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#6 /home/jlulr7ouwc1u/public_html/support/api/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#7 /home/jlulr7ouwc1u/public_html/support/api/vendor/slim/slim/Slim/Slim.php(1300):  in /home/jlulr7ouwc1u/public_html/support/api/controllers/ticket/comment.php on line 90
Help would be much appreciated.

**Comment by ivandiazwm** [comment]
It looks like the user doesn't exists. Do you have user system enabled? Have you log in using `/ticket/check` or `/user/login` and pass the token?

Anyways, we should be able to show a proper error message in this case.

**Comment by aedwards86** [comment]
i got around this by commenting out the following lines on

/api/controllers/ticket/comment.php (line 90 ish)

// if(!$user->canManageTicket($this->ticket)) {
// throw new RequestException(ERRORS::NO_PERMISSION);
// }
