### ISSUE TITLE
IMAP Issues

### ISSUE THREAD

**Issue by diogovitzo** [opensupports/opensupports#745]
When the email-polling script is run, the following exception happens:

[Fri Mar 13 18:46:11.248043 2020] [:error] [pid 8121] [client 52.44.184.94:0] PHP Fatal error:  Call to a member function isTicketSession() on null in [...redacted...]/api/controllers/ticket/comment.php on line 83

Any help? Users cant reply to tickets via e-mail atm, and new tickets cannot be converted from email

**Comment by mikeantonio772** [comment]
Having the same problem. 

My log.
[Thu Mar 19 17:45:28.531368 2020] [php7:error] [pid 6112] [client 3.228.22.206:34030] PHP Fatal error: Uncaught Error: Call to a member function isTicketSession() on null in /var/www/opensupports/api/controllers/ticket/comment.php:83\nStack trace:\n#0 /var/www/opensupports/api/controllers/system/email-polling.php(92): CommentController->handler()\n#1 /var/www/opensupports/api/libs/Controller.php(20): EmailPollingController->handler()\n#2 [internal function]: Controller->{closure}()\n#3 /var/www/opensupports/api/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)\n#4 /var/www/opensupports/api/vendor/slim/slim/Slim/Slim.php(1355): Slim\\Route->dispatch()\n#5 /var/www/opensupports/api/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\\Slim->call()\n#6 /var/www/opensupports/api/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\\Middleware\\Flash->call()\n#7 /var/www/opensupports/api/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\\Middleware\\MethodOverride->call()\n#8 /var/www/opensupports/api/vendor/slim/slim/Slim/Slim.php(1300): Slim\\Middleware\\PrettyExceptions->cal in /var/www/opensupports/api/controllers/ticket/comment.php on line 83

Studying the log i discovered that this is a problem with email replies. The code tries to comment on an existing ticket if you receive an email reply and is causing a failure. The temporary solution for me was remove the email replies from inbox.
