### ISSUE TITLE
email polling error INVALID_EMAIL when sender email address is in the management users

### ISSUE THREAD

**Issue by FRaccie** [opensupports/opensupports#890]
Our internal users cannot add tickets anymore.
We get the following error when polling the emails.

{"status":"fail","message":"EMAIL_POLLING","data":[{"author":"xxx@xxxxxxx","ticketNumber":null,"error":"Exception: INVALID_EMAIL in \/data\/sites\/web\/xxxxxxx\/subsites\/xxxxxx\/api\/controllers\/ticket\/create.php:114

**Comment by johjoh2k** [comment]
Same error here with or without attachments:

{"status":"fail","message":"EMAIL_POLLING","data":[{"author":"email@domain.tld","ticketNumber":null,"error":"Exception: INVALID_EMAIL in \/var\/www\/clients\/client1\/web2\/web\/api\/controllers\/ticket\/create.php:114\nStack trace:\n#0 \/var\/www\/clients\/client1\/web2\/web\/api\/controllers\/system\/email-polling.php(93): CreateController->handler()\n#1 \/var\/www\/clients\/client1\/web2\/web\/api\/libs\/Controller.php(20): EmailPollingController->handler()\n#2 [internal function]: Controller->{closure}()\n#3 \/var\/www\/clients\/client1\/web2\/web\/api\/vendor\/slim\/slim\/Slim\/Route.php(468): call_user_func_array(Object(Closure), Array)\n#4 \/var\/www\/clients\/client1\/web2\/web\/api\/vendor\/slim\/slim\/Slim\/Slim.php(1355): Slim\\Route->dispatch()\n#5 \/var\/www\/clients\/client1\/web2\/web\/api\/vendor\/slim\/slim\/Slim\/Middleware\/Flash.php(85): Slim\\Slim->call()\n#6 \/var\/www\/clients\/client1\/web2\/web\/api\/vendor\/slim\/slim\/Slim\/Middleware\/MethodOverride.php(92): Slim\\Middleware\\Flash->call()\n#7 \/var\/www\/clients\/client1\/web2\/web\/api\/vendor\/slim\/slim\/Slim\/Middleware\/PrettyExceptions.php(67): Slim\\Middleware\\MethodOverride->call()\n#8 \/var\/www\/clients\/client1\/web2\/web\/api\/vendor\/slim\/slim\/Slim\/Slim.php(1300): Slim\\Middleware\\PrettyExceptions->call()\n#9 \/var\/www\/clients\/client1\/web2\/web\/api\/index.php(26): Slim\\Slim->run()\n#10 {main}"}]}

**Comment by OliverTempel** [comment]
Tested from different Senders, got the error: Exception: INVALID_EMAIL 

{"0":{"author":"olivertempel@gmail.com","ticketNumber":null,"error":"Exception: INVALID_EMAIL in /var/www/clients/client1/web26/web/support/api/controllers/ticket/create.php:114\nStack trace:\n#0 /var/www/clients/client1/web26/web/support/api/controllers/system/email-polling.php(93): CreateController->handler()\n#1 /var/www/clients/client1/web26/web/support/api/libs/Controller.php(20): EmailPollingController->handler()\n#2 [internal function]: Controller->{closure}()\n#3 /var/www/clients/client1/web26/web/support/api/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)\n#4 /var/www/clients/client1/web26/web/support/api/vendor/slim/slim/Slim/Slim.php(1355): Slim\\Route->dispatch()\n#5 /var/www/clients/client1/web26/web/support/api/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\\Slim->call()\n#6 /var/www/clients/client1/web26/web/support/api/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\\Middleware\\Flash->call()\n#7 /var/www/clients/client1/web26/web/support/api/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\\Middleware\\MethodOverride->call()\n#8 /var/www/clients/client1/web26/web/support/api/vendor/slim/slim/Slim/Slim.php(1300): Slim\\Middleware\\PrettyExceptions->call()\n#9 /var/www/clients/client1/web26/web/support/api/index.php(26): Slim\\Slim->run()\n#10 {main}"}}

**Comment by johjoh2k** [comment]
Waiting for the correct resolution, to continue working with OpenSupports, you can:
- edit /api/controllers/ticket/create.php
- comment out line 114, 115 and 116:
//if(!Staff::getUser($this->email,'email')->isNull() || $this->isEmailInvalid()) {
//    throw new Exception(ERRORS::INVALID_EMAIL);
//}
- save and try.

**Comment by OliverTempel** [comment]
Doesnt work, next error pops up:

{"0":{"author":"email@domain.com","ticketNumber":null,"error":"Exception: Invalid prop: tickets in /var/www/clients/client1/web26/web/support/api/models/DataStore.php:102\nStack trace:\n#0 /var/www/clients/client1/web26/web/support/api/controllers/ticket/create.php(202): DataStore->__set('tickets', 1)\n#1 /var/www/clients/client1/web26/web/support/api/controllers/ticket/create.php(121): CreateController->storeTicket()\n#2 /var/www/clients/client1/web26/web/support/api/controllers/system/email-polling.php(93): CreateController->handler()\n#3 /var/www/clients/client1/web26/web/support/api/libs/Controller.php(20): EmailPollingController->handler()\n#4 [internal function]: Controller->{closure}()\n#5 /var/www/clients/client1/web26/web/support/api/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)\n#6 /var/www/clients/client1/web26/web/support/api/vendor/slim/slim/Slim/Slim.php(1355): Slim\\Route->dispatch()\n#7 /var/www/clients/client1/web26/web/support/api/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\\Slim->call()\n#8 /var/www/clients/client1/web26/web/support/api/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\\Middleware\\Flash->call()\n#9 /var/www/clients/client1/web26/web/support/api/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\\Middleware\\MethodOverride->call()\n#10 /var/www/clients/client1/web26/web/support/api/vendor/slim/slim/Slim/Slim.php(1300): Slim\\Middleware\\PrettyExceptions->call()\n#11 /var/www/clients/client1/web26/web/support/api/index.php(26): Slim\\Slim->run()\n#12 {main}"}}

**Comment by OliverTempel** [comment]
Currently looking threw the code.
All E-Mails would deleted after imap call, thats bad, cause the exception above, not processed emails would be deleted also. It would be better to mark correct processed mails as read and delete all mails which marked as read at the end.

**Comment by OliverTempel** [comment]
Any suggestions?

**Comment by FRaccie** [comment]
> Any suggestions?

Is the userbase for management and users a different table?
Cause, there should be no reason why a manager and a normal user cannot have 2 accounts then...

**Comment by FRaccie** [comment]
> Waiting for the correct resolution, to continue working with OpenSupports, you can:
> 
> * edit /api/controllers/ticket/create.php
> * comment out line 114, 115 and 116:
>   //if(!Staff::getUser($this->email,'email')->isNull() || $this->isEmailInvalid()) {
>   //    throw new Exception(ERRORS::INVALID_EMAIL);
>   //}
> * save and try.

This works fine :
Thanks for the suggestion

//        if(!Staff::getUser($this->email,'email')->isNull() || $this->isEmailInvalid()) {
	if($this->isEmailInvalid()) {
            throw new Exception(ERRORS::INVALID_EMAIL);
        }

**Comment by de2001** [comment]
I had the same Problem. If i comment these lines, there is a new error.

  `{"status":"fail","message":"EMAIL_POLLING","data":[{"author":"xxxxx@xxxxxx.xx","ticketNumber":null,"error":"ErrorException: Trying to access array offset on value of type null in C:\\xampp\\htdocs\\opensupports\\api\\models\\DataStore.php:130\nStack trace:\n#0 C:\\xampp\\htdocs\\opensupports\\api\\models\\DataStore.php(130): Slim\\Slim::handleErrors(8, 'Trying to acces...', 'C:\\\\xampp\\\\htdocs...', 130, Array)\n#1 C:\\xampp\\htdocs\\opensupports\\api\\models\\DataStore.php(108): DataStore->parseBeanProp('email')\n#2 C:\\xampp.........................................`

**Comment by 5SpaceItaly** [comment]
SOLVED!!!
Like @FRaccie says:
> - edit /api/controllers/ticket/create.php
> - comment out line 115 and add "if($this->isEmailInvalid()) {":
>   //        if(!Staff::getUser($this->email,'email')->isNull() || $this->isEmailInvalid()) {
>   if($this->isEmailInvalid()) {
>         throw new Exception(ERRORS::INVALID_EMAIL);
>   }
> -  save and try.

Then, **for registerd users**, works. To make works for unregisted user, comment line below 118 and 120 (**not 119!!!**):
```
        //if(!Controller::isLoginMandatory() && !Controller::isStaffLogged() && !Controller::isUserLogged()  && !User::getUser($this->email, 'email')->email){
            $this->createNewUser();
        //}
```

make sure not comment line 119 $this->createNewUser();
Don't worries, if the user exists this method don't recreate it!

Happy coding

**Comment by de2001** [comment]
After that there is this error:

`            "error": "ErrorException: Trying to access array offset on value of type null in C:\\xampp\\htdocs\\opensupports\\api\\models\\DataStore.php:130\nStack trace:\n#0 C:\\xampp\\htdocs\\opensupports\\api\\models\\DataStore.php(130): Slim\\Slim::handleErrors(8, 'Trying to acces...', 'C:\\\\xampp\\\\htdocs...', 130, Array)\n#1 C:\\xampp\\htdocs\\opensupports\\api\\models\\DataStore.php(108): DataStore->parseBeanProp('email')\n#2 C:\\xampp\\htdocs\\opensupports\\api\\controllers\\ticket\\create.php(236): DataStore->__get('email')\n#3 C:\\xampp\\htdocs\\opensupports\\api\\controllers\\ticket\\create.php(174): CreateController->getAuthor()\n#4 C:\\xampp\\htdocs\\opensupports\\api\\controllers\\ticket\\create.php(122): CreateController->storeTicket()\n#5 C:\\xampp\\htdocs\\opensupports\\api\\controllers\\system\\email-polling.php(93): CreateController->handler()\n#6 C:\\xampp\\htdocs\\opensupports\\api\\libs\\Controller.php(20): EmailPollingController->handler()\n#7 [internal function]: Controller->{closure}()\n#8 C:\\xampp\\htdocs\\opensupports\\api\\vendor\\slim\\slim\\Slim\\Route.php(468): call_user_func_array(Object(Closure), Array)\n#9 C:\\xampp\\htdocs\\opensupports\\api\\vendor\\slim\\slim\\Slim\\Slim.php(1355): Slim\\Route->dispatch()\n#10 C:\\xampp\\htdocs\\opensupports\\api\\vendor\\slim\\slim\\Slim\\Middleware\\Flash.php(85): Slim\\Slim->call()\n#11 C:\\xampp\\htdocs\\opensupports\\api\\vendor\\slim\\slim\\Slim\\Middleware\\MethodOverride.php(92): Slim\\Middleware\\Flash->call()\n#12 C:\\xampp\\htdocs\\opensupports\\api\\vendor\\slim\\slim\\Slim\\Middleware\\PrettyExceptions.php(67): Slim\\Middleware\\MethodOverride->call()\n#13 C:\\xampp\\htdocs\\opensupports\\api\\vendor\\slim\\slim\\Slim\\Slim.php(1300): Slim\\Middleware\\PrettyExceptions->call()\n#14 C:\\xampp\\htdocs\\opensupports\\api\\index.php(26): Slim\\Slim->run()\n#15 {main}"
`

**Comment by dotupNET** [comment]
This is the correct solution:

    private function getAuthor()
    {
        if (Controller::getLoggedUser()->email === $this->email) {
            return Controller::getLoggedUser();
        } else {
            return User::getUser($this->email, 'email');
        }
    }

**Comment by junado-fsigges** [comment]
Pardon me if I'm missing something, but how can this still be an issue? Considering the above, it seems like the fix is there. Why is this still not fixed over three years later? I understand that the project slowed down but this is a function that is so essential that everyone should trip over it who is trying to receive tickets from unregistered users via e-mail.
