### ISSUE TITLE
e-mail polling error

### ISSUE THREAD

**Issue by hartmanrik** [opensupports/opensupports#924]
Everything went fine while setting up OpenSupports. No problems with setting up an Office365 account and sending mails.
No errors when setting up the imap settings.

When I use the polling post request, I'll get the following error most of the time: (sometimes it works when trying to create a ticket sent with from an gmail address)

`{"status":"fail","message":"EMAIL_POLLING","data":[{"author":"####@gmail.com","ticketNumber":null,"error":"ErrorException: Invalid argument supplied for foreach() in \/home\/########\/domains\/########.nl\/public_html\/opensupports\/api\/libs\/DataStoreList.php:8\nStack trace:\n#0 \/home\/########\/domains\/########.nl\/public_html\/opensupports\/api\/libs\/DataStoreList.php(8): Slim\\Slim::handleErrors(2, 'Invalid argumen...', '\/home\/########\/...', 8, Array)\n#1 \/home\/########\/domains\/########.nl\/public_html\/opensupports\/api\/models\/DataStore.php(134): DataStoreList::getList('Ticket', NULL)\n#2 \/home\/########\/domains\/########.nl\/public_html\/opensupports\/api\/models\/DataStore.php(108): DataStore->parseBeanProp('sharedTicketLis...')\n#3 \/home\/########\/domains\/########.nl\/public_html\/opensupports\/api\/controllers\/ticket\/create.php(199): DataStore->__get('sharedTicketLis...')\n#4 \/home\/########\/domains\/########.nl\/public_html\/opensupports\/api\/controllers\/ticket\/create.php(121): CreateController->storeTicket()\n#5 \/home\/########\/domains\/########.nl\/public_html\/opensupports\/api\/controllers\/system\/email-polling.php(93): CreateController->handler()\n#6 \/home\/########\/domains\/########.nl\/public_html\/opensupports\/api\/libs\/Controller.php(20): EmailPollingController->handler()\n#7 [internal function]: Controller->{closure}()\n#8 \/home\/########\/domains\/########.nl\/public_html\/opensupports\/api\/vendor\/slim\/slim\/Slim\/Route.php(468): call_user_func_array(Object(Closure), Array)\n#9 \/home\/########\/domains\/########.nl\/public_html\/opensupports\/api\/vendor\/slim\/slim\/Slim\/Slim.php(1355): Slim\\Route->dispatch()\n#10 \/home\/########\/domains\/########.nl\/public_html\/opensupports\/api\/vendor\/slim\/slim\/Slim\/Middleware\/Flash.php(85): Slim\\Slim->call()\n#11 \/home\/########\/domains\/########.nl\/public_html\/opensupports\/api\/vendor\/slim\/slim\/Slim\/Middleware\/MethodOverride.php(92): Slim\\Middleware\\Flash->call()\n#12 \/home\/########\/domains\/########.nl\/public_html\/opensupports\/api\/vendor\/slim\/slim\/Slim\/Middleware\/PrettyExceptions.php(67): Slim\\Middleware\\MethodOverride->call()\n#13 \/home\/########\/domains\/########.nl\/public_html\/opensupports\/api\/vendor\/slim\/slim\/Slim\/Slim.php(1300): Slim\\Middleware\\PrettyExceptions->call()\n#14 \/home\/########\/domains\/########.nl\/public_html\/opensupports\/api\/index.php(26): Slim\\Slim->run()\n#15 {main}"}]}`

It always throws this error when sending from the same domain as the one set up in the email settings.

Unfortunately I didn't fine anyone with the same error...
Could someone help me out? Very much appreciated!

**Comment by dotupNET** [comment]
https://github.com/opensupports/opensupports/issues/890#issuecomment-799883783

**Comment by riddlenl** [comment]
I have this same error popping up, but no matching examples in issue #890 
@hartmanrik did you fix this?
