### ISSUE TITLE
Unable to generate ticket from email

### ISSUE THREAD

**Issue by akashsemil** [opensupports/opensupports#963]
[root@localhost ~]# curl -d "token=IIyGUVOrWQwnSVPEj9nP" -X POST http://localhost/api/system/email-polling
{"status":"fail","message":"EMAIL_POLLING","data":[{"author":"akashsemil@outlook.com","ticketNumber":null,"error":"ErrorException: Trying to access array offset on value of type null in \/var\/www\/opensupport\/api\/models\/DataStore.php:130\nStack trace:\n#0 \/var\/www\/opensupport\/api\/models\/DataStore.php(130): Slim\\Slim::handleErrors()\n#1 \/var\/www\/opensupport\/api\/models\/DataStore.php(108): DataStore->parseBeanProp()\n#2 \/var\/www\/opensupport\/api\/controllers\/ticket\/create.php(117): DataStore->__get()\n#3 \/var\/www\/opensupport\/api\/controllers\/system\/email-polling.php(93): CreateController->handler()\n#4 \/var\/www\/opensupport\/api\/libs\/Controller.php(20): EmailPollingController->handler()\n#5 [internal function]: Controller->{closure}()\n#6 \/var\/www\/opensupport\/api\/vendor\/slim\/slim\/Slim\/Route.php(468): call_user_func_array()\n#7 \/var\/www\/opensupport\/api\/vendor\/slim\/slim\/Slim\/Slim.php(1355): Slim\\Route->dispatch()\n#8 \/var\/www\/opensupport\/api\/vendor\/slim\/slim\/Slim\/Middleware\/Flash.php(85): Slim\\Slim->call()\n#9 \/var\/www\/opensupport\/api\/vendor\/slim\/slim\/Slim\/Middleware\/MethodOverride.php(92): Slim\\Middleware\\Flash->call()\n#10 \/var\/www\/opensupport\/api\/vendor\/slim\/slim\/Slim\/Middleware\/PrettyExceptions.php(67): Slim\\Middleware\\MethodOverride->call()\n#11 \/var\/www\/opensupport\/api\/vendor\/slim\/slim\/Slim\/Slim.php(1300): Slim\\Middleware\\PrettyExceptions->

**Comment by campio97** [comment]
Hello, i have the same problem.
How to resolve it?

**Comment by tareco** [comment]
In the case someone still looking for a solution.

I realised that the error message is of type `E_NOTICE` and in my case `error_reporting` was not filtering them out.

Adding `& ~E_NOTICE` to `php.ini` has solved it for me:

```
$ grep ^error_reporting /etc/php/7.4/apache2/php.ini
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE
```
