### ISSUE TITLE
Cannot add images to articles or tickets.

### ISSUE THREAD

**Issue by superturrican** [opensupports/opensupports#985]
Every time I try and add an image using the editor to an article or a ticket, the save button doesn't do anything when I click on it.

The console log is showing as follows:
`request /article/edit`
`Object { content: "<p>Left</p><p class=\"ql-align-right\">Right</p><p class=\"ql-align-center\">Centre</p><p class=\"ql-align-justify\">Justified - \"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation <em>ullamco</em> laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\"</p><p class=\"ql-align-justify\"><br></p><p class=\"ql-align-justify\"><a href=\"https://domain.link\" rel=\"noopener noreferrer\" target=\"_blank\">test</a></p><p class=\"ql-align-justify\"><img src=\"IMAGE_PATH_0\"></p>", images: 1, image_0: File, articleId: "2", title: "Test" }`
`bundle.js:9:72092`
`https://domain.name/api/article/edit`
`[HTTP/2 500 Internal Server Error 705ms]`
`INVALID REQUEST to: /article/edit bundle.js:9:72608`
`undefined bundle.js:9:72646`
`Uncaught (in promise)`
`Object { status: "fail", message: "Internal server error" }`
The server error.log is showing this line:
`PHP Fatal error:  Uncaught Error: Class 'finfo' not found in /home/myuser/domain.name/api/vendor/codeguy/upload/src/Upload/File.php:203`
`Stack trace:`
`#0 /home/username/domain.name/api/vendor/codeguy/upload/src/Upload/Validation/Mimetype.php(75): Upload\File->getMimetype()`
`#1 /home/username/domain.name/api/vendor/codeguy/upload/src/Upload/File.php(282): Upload\Validation\Mimetype->validate(Object(Upload\File))`
`#2 /home/username/domain.name/api/vendor/codeguy/upload/src/Upload/File.php(323): Upload\File->validate()`
`#3 /home/username/domain.name/api/libs/FileUploader.php(51): Upload\File->upload()`
`#4 /home/username/domain.name/api/libs/Controller.php(121): FileUploader->upload('image_0')`
`#5 /home/username/domain.name/api/controllers/article/edit.php(76): Controller->uploadImages(true)`
`#6 /home/username/domain.name/api/libs/Controller.php(20): EditArticleController->handler()`
`#7 [internal function]: Controller->{closure}()`
`#8 /home/username/domain.name/api/vendor/slim in /home/username/domain.name/api/vendor/codeguy/upload/src/Upload/File.php on line 203`

**Comment by superturrican** [comment]
My shared host didn't have fileinfo enabled, so problem resolved.
